baseURL = "http://localhost:1313/"
languageCode = "ja-ja"
title = "Easlerのぶろぐ"
theme = "hugo-lamp"
googleAnalytics = "UA-XXX-X"          # Google Analytics UA number

[params]
  mainSections = ["posts"]
  subtitle = "とりあえず記事を書くよ"
  author = "Huy Nguyen"
  logo = "/img/avatar.jpg"
  description = "A light responsive Hugo AMP theme for blogger"
  paginate = 10

  # Publisher
  ## adsensePublisher = "ca-pub-XXX"    # Required if you want to include Google Adsense
  adsenseSlot = "XXX"                   # Required slot to display ads
  adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Hugo Blog Title (SEO Version)"
  googleSiteVerification = "google_site_verification_code"    # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

  # Social networks
  #email = "name@domain.com"
  github = "Easler001"
  twitter = "a41908657"
  linkedin = "linkedin_username"
  #facebook = "facebook_username"
  #google = "googleplus_id_number"
  #instagram = "instagram_username"
  #youtube = "youtube_username"
  #dribbble = "dribbble_username"
  #reddit = "reddit_username"

[taxonomies]
  tag = "tags"
  category = "categories"
